### ISSUE TITLE
Failure to decode transaction XDR

### ISSUE THREAD

**Issue by avolkov-dev** [elucidsoft/dotnetcore-stellar-sdk#334]
**Describe the bug**
Latest SDK (stellar-dotnet-sdk version 7.1.30) not able to decode `ResultXdr`

**To Reproduce**
Run code:
```
using System;
using System.Linq;
using System.Threading.Tasks;
using stellar_dotnet_sdk;
using Xunit;
using stellar_dotnet_sdk.xdr;

namespace Tests
{
    public class DecodeFail
    {
        [Fact]
        public async Task FailsToDecodeTx()
        {
            var server = new Server("https://horizon-testnet.stellar.org/");
            var txPage = await server.Transactions
                .ForLedger(349089)
                .Limit(100)
                .IncludeFailed(true)
                .Execute();

            //http://testnet.stellarchain.io/tx/a6751fc111031c878041c781d7da8ceab06ebd2497d51d7bfe31106c8c22717d
            var tx = txPage.Records
                .Single(x=>x.Hash == "a6751fc111031c878041c781d7da8ceab06ebd2497d51d7bfe31106c8c22717d");
            var xdr = Convert.FromBase64String(tx.ResultXdr);
            TransactionResult.Decode(new XdrDataInputStream(xdr));
        }
    }
}


```

And receive error:
```
Tests.DecodeFail.FailsToDecodeTx

System.Exception: Unknown enum value: 1

System.Exception
Unknown enum value: 1
   at stellar_dotnet_sdk.xdr.PublicKeyType.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.PublicKey.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.AccountID.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.ClaimOfferAtom.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.ManageOfferSuccessResult.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.ManageBuyOfferResult.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.OperationResult.OperationResultTr.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.OperationResult.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.TransactionResult.TransactionResultResult.Decode(XdrDataInputStream stream)
   at stellar_dotnet_sdk.xdr.TransactionResult.Decode(XdrDataInputStream stream)
   at Tests.DecodeFail.FailsToDecodeTx() in D:\Projects\Swisschain\Sirius.Integrations.Stellar\tests\Tests\DecodeFail.cs:line 27
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

**Expected behavior**
No error occured

**Comment by Kirbyrawr** [comment]
Hi, i'm checking this but i can't seem to reproduce the bug, i literally copied your code and it decode it properly.
